# Generated by Django 4.1.3 on 2022-11-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_material_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
